### ISSUE TITLE
support webpack4?

### ISSUE THREAD

**Issue by cixiu** [geowarin/friendly-errors-webpack-plugin#62]
webpack4 has published, can u update this plugin for support webpack4?

**Comment by sschadwick** [comment]
Why did you close this? This plugin currently works with webpack 4, however it is throwing deprecation warnings.

**Comment by Rowno** [comment]
The exact deprecation warning for reference:
```
(node:29743) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at FriendlyErrorsWebpackPlugin.apply (./node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:39:14)
    at webpack (./node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (./node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (./node_modules/webpack-cli/bin/webpack.js:510:3)
    at Object.parse (./node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at ./node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (./node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by MartinX3** [comment]
Same here

```
(node:10213) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at FriendlyErrorsWebpackPlugin.apply (./node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:39:14)
    at webpack (./node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (./node_modules/webpack-cli/bin/webpack.js:436:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

**Comment by s00d** [comment]
Just replace all compiler.plugin('hookName', ...) calls with compiler.hook.[hookName].tap or compiler.hook.[hookName].tapAsync if it's asynchronous and gets a callback as an argument.
